Build requirements:
- Android SDK
- Android NDK rev 8 or above
- Apache Ant

Create local.properties file in project folder: 
sdk.dir=<Andorid SDK dir>
ndk.dir=<Andorid NDK dir>

Debug build: ant debug
Release build: ant release

More info on android command line build:
http://developer.android.com/guide/developing/building/building-cmdline.html

